// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqnhj67W3twgpV4Txax3bJyEZg6BI2vd4',
    appId: '1:439193351769:web:ff0e2cd4e31016b818a348',
    messagingSenderId: '439193351769',
    projectId: 'hr-management-system-abdo-2026',
    authDomain: 'hr-management-system-abdo-2026.firebaseapp.com',
    storageBucket: 'hr-management-system-abdo-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO8zqw7ltlBHZfTQAuHHt3nZlqZrzYnwg',
    appId: '1:439193351769:android:8c13f239308139cd18a348',
    messagingSenderId: '439193351769',
    projectId: 'hr-management-system-abdo-2026',
    storageBucket: 'hr-management-system-abdo-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfc58tuxmJgjrU9P4AMlXnYbcuZuDltyM',
    appId: '1:439193351769:ios:85571c70ba228cc018a348',
    messagingSenderId: '439193351769',
    projectId: 'hr-management-system-abdo-2026',
    storageBucket: 'hr-management-system-abdo-2026.firebasestorage.app',
    iosBundleId: 'com.example.hrManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfc58tuxmJgjrU9P4AMlXnYbcuZuDltyM',
    appId: '1:439193351769:ios:85571c70ba228cc018a348',
    messagingSenderId: '439193351769',
    projectId: 'hr-management-system-abdo-2026',
    storageBucket: 'hr-management-system-abdo-2026.firebasestorage.app',
    iosBundleId: 'com.example.hrManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqnhj67W3twgpV4Txax3bJyEZg6BI2vd4',
    appId: '1:439193351769:web:5e00455e2c100dcc18a348',
    messagingSenderId: '439193351769',
    projectId: 'hr-management-system-abdo-2026',
    authDomain: 'hr-management-system-abdo-2026.firebaseapp.com',
    storageBucket: 'hr-management-system-abdo-2026.firebasestorage.app',
  );
}
